In [2]:
import pandas as pd
import numpy as np
import sqlalchemy
from pathlib import Path

In [3]:
!pwd

/home/vijay/fde26/data

In [4]:
# DATA_DIR = Path("./data")
# customers     = pd.read_csv("olist_customers_dataset.csv")
geolocation   = pd.read_csv("olist_geolocation_dataset.csv")
orders        = pd.read_csv("olist_orders_dataset.csv")
order_items   = pd.read_csv("olist_order_items_dataset.csv")
order_payments= pd.read_csv("olist_order_payments_dataset.csv")
order_reviews = pd.read_csv("olist_order_reviews_dataset.csv")
# products      = pd.read_csv("olist_products_dataset.csv")
# sellers       = pd.read_csv("olist_sellers_dataset.csv")
category_trans= pd.read_csv("product_category_name_translation.csv")

In [9]:
order_payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 8.1 MB

In [8]:
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [46]:
orders["order_purchase_timestamp"] = pd.to_datetime(orders["order_purchase_timestamp"])
orders.sort_values("order_purchase_timestamp").iloc[500:550]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
71677,24e1c731364b64c76d98e985bfdbef77,679b47a0e9e57e5f32b43a333b746f55,delivered,2017-01-17 20:38:15,2017-01-17 20:50:16,2017-01-19 09:26:02,2017-01-23 10:38:08,2017-02-27 00:00:00
4609,fdb3ef83ea6f7bef7d13bdd9b38da661,fbc1bec47970c387d5f4962d518dd268,delivered,2017-01-17 21:09:40,2017-01-17 21:21:39,2017-01-24 14:49:32,2017-01-26 16:25:11,2017-03-13 00:00:00
43347,ecfdcaa1a2dacb4e5297d8251b115002,2dffab2135e36d25087cad94f4e559ab,delivered,2017-01-17 22:26:00,2017-01-17 22:42:15,2017-01-19 08:14:56,2017-01-27 10:07:33,2017-03-07 00:00:00
63522,3aa9ae345c5bf7396e8b237717c470cf,d14ec9b10324e4132ee110e8012e7dde,delivered,2017-01-17 22:34:59,2017-01-17 22:45:15,2017-01-26 08:08:31,2017-02-01 16:48:47,2017-02-23 00:00:00
69978,b063bf13bfec7c847d7a6bdb54554c00,9116afdef84d57d567a2d87cc9dd12bc,delivered,2017-01-17 23:37:51,2017-01-17 23:50:17,2017-01-18 10:07:14,2017-01-25 13:53:45,2017-02-27 00:00:00
48658,c022b7da8ab7a4a04bd561c8f765a14a,c797ffdbae65b56c177d3c1368d03628,delivered,2017-01-17 23:40:42,2017-01-17 23:50:15,2017-01-18 13:59:38,2017-01-25 12:51:51,2017-03-01 00:00:00
55591,b8297ee8722ce94cc9a2e9263124cd36,7c852d7bbf1b4c00b69926f3b380e288,delivered,2017-01-18 00:31:51,2017-01-18 00:45:47,2017-01-18 10:32:15,2017-01-30 11:51:53,2017-03-02 00:00:00
25136,0f91be4a9bf9ffd2c1ace53b9e5dd9e2,3dd2f8a8b58ffd06e8bff60f30b84f91,delivered,2017-01-18 02:01:36,2017-01-23 16:43:02,2017-01-26 14:44:01,2017-01-30 11:04:23,2017-03-02 00:00:00
81699,99e3f90c535337b45eace6f8a8a9400f,3d5c479107dce026a67c0a78ec5f87f2,delivered,2017-01-18 08:01:37,2017-01-18 08:10:14,2017-01-18 11:03:09,2017-01-26 15:14:31,2017-03-17 00:00:00
67939,fbd82b1fe98967de0db29b6cf134d00a,45f5c9d984dbfa2105e3544cc85133bf,delivered,2017-01-18 08:55:36,2017-01-18 09:05:10,2017-01-18 10:41:58,2017-03-07 08:55:47,2017-02-14 00:00:00
85488,6ed4f19dc97f2a4b5d0f15651247dbca,6b7e649105e4c5388bd8c3c4e9efcff3,processing,2017-01-18 09:52:32,2017-01-18 10:05:11,NaN,NaN,2017-02-28 00:00:00
28298,660c604f50fc9edcf854689682d1560e,d20bbabb669a554138e7d3f97cafafd6,delivered,2017-01-18 10:27:19,2017-01-18 10:42:18,2017-01-18 12:05:00,2017-01-20 11:42:06,2017-02-24 00:00:00
75396,71f86189760ff1dec6805f4fc7c6f52f,bc41a708ec6dabfa8b01320ad60ac6a2,delivered,2017-01-18 10:42:05,2017-01-18 10:50:21,2017-01-18 17:19:08,2017-01-31 16:59:08,2017-03-10 00:00:00
28122,7ead6c8726098bd70de2b16cac42df74,19d8d28432946239ce9f75e1990f7e58,delivered,2017-01-18 10:55:55,2017-01-19 02:11:04,2017-01-19 11:35:16,2017-02-09 07:14:02,2017-03-10 00:00:00
81138,0e660617f70b9a3f6bfd3919b49450ab,3bb3946913ea760c53bc4298f9ecf5bd,delivered,2017-01-18 11:14:16,2017-01-18 11:30:09,2017-01-20 11:05:50,2017-01-26 14:44:45,2017-02-21 00:00:00
32567,8c0a4c58ee098fea192d86cb195786e6,743eb1a642f457af79087cfaa894a63b,delivered,2017-01-18 12:27:53,2017-01-18 12:41:46,2017-01-19 15:55:22,2017-01-30 11:47:28,2017-03-10 00:00:00
48411,0a1ad2c293c3baacc6b2c2d442c71acd,3257a8d4cbb3343dcf40eac13ba329cb,delivered,2017-01-18 12:51:23,2017-01-18 13:05:15,2017-01-23 13:03:31,2017-02-06 16:56:48,2017-02-16 00:00:00
63139,7e6b55f6388682bf51a05d8f13c2d466,9a3f62a5bf3676fc5f7197d68d626515,invoiced,2017-01-18 12:59:05,2017-01-18 13:10:17,NaN,NaN,2017-03-02 00:00:00
90790,3ac963599c50b9beedbcebb47eb33af9,ab23392115ab5083ec640a5c781c2820,delivered,2017-01-18 14:32:43,2017-01-18 14:45:21,2017-02-07 08:12:41,2017-02-16 17:42:20,2017-03-02 00:00:00
33110,1ef09d75953043a71a73428e15bc2f5c,572178b4530a9a986a59205bedea0712,delivered,2017-01-18 14:53:29,2017-01-19 06:50:22,2017-01-20 10:57:54,2017-01-25 15:06:36,2017-02-24 00:00:00
95837,c9645496b715730a1a5d07eb97a6bf6b,65b9f936439ccafa20f0d6888a5875d3,delivered,2017-01-18 14:56:47,2017-01-24 15:25:11,2017-01-25 10:07:43,2017-01-30 13:13:54,2017-02-14 00:00:00
19437,f6b63a36cd2dd4fd184e6da3f911a4de,f0dae1e937bb3c41846089b13dde866e,delivered,2017-01-18 15:31:13,2017-01-20 02:15:28,2017-01-20 10:50:47,2017-01-25 08:58:55,2017-03-02 00:00:00
21844,171398a0cd843c65ac78aee9e05a1f49,f0244902c07b7c0799e468218579a925,delivered,2017-01-18 16:07:37,2017-01-18 16:15:20,2017-01-23 10:02:30,2017-02-03 12:51:58,2017-03-20 00:00:00
62904,90d2bbc31356e711e2fe7b0b78181687,58fd1de47b74bd72637ccb4179c475bc,delivered,2017-01-18 16:48:00,2017-01-19 02:15:58,2017-01-20 16:34:12,2017-01-24 19:02:18,2017-02-28 00:00:00
42634,c5e86e382215a14b35e8a51f1110f39d,f09f24eded6cdd153f9c3d778168b564,delivered,2017-01-18 17:04:36,2017-01-18 17:15:18,2017-01-20 17:28:13,2017-02-03 12:09:19,2017-02-28 00:00:00
37081,5dc269b7c4dce1624653e914a1b739f5,575a192461d4a325e5f9667e6ce5c2df,delivered,2017-01-18 17:20:39,2017-01-18 17:31:55,2017-01-20 13:02:22,2017-01-27 12:09:42,2017-02-24 00:00:00
97065,5a37429384be05ca14780e4989543688,03b753419e88796de2c7127ff13dce58,delivered,2017-01-18 17:42:22,2017-01-18 17:55:09,2017-01-23 11:19:08,2017-02-06 13:33:56,2017-02-28 00:00:00
6307,77c34615b2963e4bf4b48d59da0eb5e1,06b74967617d6e12688e779fdc1a580c,delivered,2017-01-18 17:44:05,2017-01-18 19:05:09,2017-01-20 11:45:44,2017-01-31 10:41:44,2017-02-16 00:00:00
79831,00b4a910f64f24dbcac04fe54088a443,d70e5eac00a9d35a3cb193442c0287cd,delivered,2017-01-18 17:55:34,2017-01-18 18:05:17,2017-01-19 14:44:25,2017-01-26 13:21:57,2017-02-28 00:00:00
20492,d0a4948ce19a51837d5e24c26ab83d76,ff84d0fa669f79bdc394cadf5d651cf2,delivered,2017-01-18 19:39:51,2017-01-18 19:50:23,2017-01-24 08:48:51,2017-01-31 09:15:04,2017-03-13 00:00:00
12195,e2d092db21e901d04985350bf0e748ac,08fbfcc1b6c48f73ddca8312c78f6f53,delivered,2017-01-18 20:11:57,2017-01-18 20:25:10,2017-01-22 21:41:59,2017-01-27 09:37:35,2017-02-28 00:00:00
27709,3a6cac3e6717e6a7ee4cb28aaa149a91,766d9773a9cfa50e19a5c27a88d1b911,delivered,2017-01-18 20:14:17,2017-01-18 20:25:12,2017-01-20 11:07:49,2017-01-27 17:14:19,2017-02-20 00:00:00
31699,a68667474430fadbcfc1bfbb9e2adc0b,616fa20bdc978ccaf552b46fbc0567a5,processing,2017-01-18 20:48:59,2017-01-20 02:10:55,NaN,NaN,2017-03-06 00:00:00
82872,2511cdf205337513507a1863f0098d39,71058039e9883484d1264522cbc9c2f1,delivered,2017-01-18 21:08:18,2017-01-19 21:10:20,2017-01-24 07:21:21,2017-01-26 21:57:38,2017-02-28 00:00:00
75504,9c0b834fc89f4dd70679baffe8bed38e,3ff64bf4067f2b8c240397252473423b,delivered,2017-01-18 22:12:34,2017-01-18 22:25:08,2017-01-19 12:37:06,2017-01-26 13:28:50,2017-02-14 00:00:00
81272,fcda3cc8210e746326864eb933641ccf,fee7cf49127308e2b5402c9984b6f1f6,delivered,2017-01-18 22:41:55,2017-01-20 22:42:02,2017-01-23 11:41:56,2017-01-31 18:47:35,2017-03-02 00:00:00
54598,95fd5e469d8ce5093adeace50b5a4389,073a1dd224494392bd923c55a093ce4e,delivered,2017-01-18 22:57:25,2017-01-18 23:10:21,2017-01-19 15:30:35,2017-01-24 13:44:49,2017-02-14 00:00:00
83892,e1000df659259b29cb73a4798ccd7454,feb21f4291037a45288a6266d66a0096,delivered,2017-01-18 23:02:45,2017-01-18 23:10:20,2017-01-19 15:02:12,2017-02-09 12:33:46,2017-02-28 00:00:00
89233,7b4fb0197b18a0fd0e75f9e44b3fc757,7c495c9a1dbeeb7167642f15ae11bab8,delivered,2017-01-18 23:15:29,2017-01-18 23:30:12,2017-01-19 14:47:45,2017-01-30 09:33:41,2017-03-08 00:00:00
91131,facac214a771c262175219d6c5a3a439,d577d6f224cc6476bfea34715dcb4a12,delivered,2017-01-19 00:08:11,2017-01-19 00:15:43,2017-01-20 13:41:44,2017-01-30 14:41:21,2017-03-01 00:00:00
50339,b79559dba6909e4d8ac0ddf501a99f14,8875aea6f056699f247e669173862026,delivered,2017-01-19 08:57:04,2017-01-19 21:01:51,2017-01-20 10:18:48,2017-01-27 09:15:53,2017-02-27 00:00:00
91450,f878206572adfa47110fed4947806589,1b68647cee091c5dcf4f7200ba5dd760,delivered,2017-01-19 09:59:49,2017-01-19 10:10:14,2017-01-20 11:03:56,2017-01-26 15:48:46,2017-03-13 00:00:00
75350,4a571f5e71e16ce232386c80d485db65,a08c3f511f37158bd7e1964e6efafa2a,delivered,2017-01-19 10:17:29,2017-01-19 10:30:18,2017-01-23 11:19:07,2017-02-01 01:05:18,2017-03-03 00:00:00
35036,984d046c833232079162e22c7ef8c15d,6cdb70bd1221c6913ebb68b580713161,delivered,2017-01-19 10:33:22,2017-01-19 10:41:43,2017-01-20 13:57:33,2017-01-26 13:05:06,2017-03-01 00:00:00
39956,5d6e9993ecc20a59e637ce711858d081,47fd93db3f6e715f6d06f90ba501b94d,delivered,2017-01-19 11:26:57,2017-01-24 15:35:15,2017-03-13 09:16:51,2017-03-23 08:21:38,2017-02-27 00:00:00
24536,e5ecfcbdbc07f8edf7ec0df1504a74a6,db329a00354d35ec9fdaaf8e11bd8033,delivered,2017-01-19 11:47:55,2017-01-19 13:30:21,2017-01-27 12:24:41,2017-02-06 13:43:56,2017-02-17 00:00:00
54547,77e102ecf08e057581ef2ce55c80c6c0,4cd81e890532dc8cf4ee9c2667629e43,delivered,2017-01-19 12:02:28,2017-01-19 12:21:38,2017-01-23 11:58:06,2017-01-26 11:12:14,2017-02-15 00:00:00
26800,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaN,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01 00:00:00
80659,bcb093f60b7e48f285bf92f681e65651,fc65613a333059225d516c273fbff1c0,delivered,2017-01-19 13:06:45,2017-01-21 03:10:24,2017-01-23 21:44:04,2017-01-26 13:33:59,2017-02-15 00:00:00
27259,10bce195e3966122a3dd0e2aa676f761,0280e2736a179aa87a59447236a797fa,delivered,2017-01-19 13:38:16,2017-01-20 13:45:08,2017-01-24 07:47:43,2017-01-27 10:42:38,2017-02-21 00:00:00

In [ ]:
# Assuming you already loaded the dataframes
order_items_sorted = order_items.sort_values(
    by="shipping_limit_date", 
    ascending=True
)

# Show result
order_items_sorted[["order_id", "order_item_id", "product_id", 
                    "seller_id", "shipping_limit_date", "price"]].head(20)

In [35]:
products["product_description_lenght"].max()

np.float64(3992.0)

In [34]:
print(products["product_category_name"].str.len().max())

46.0

In [6]:
# ============================================================
# 3. Quick overview of every table
# ============================================================
for name, df in tables.items():
    print("=" * 70)
    print(f"📌 {name.upper()}  |  shape = {df.shape}")
    print("-" * 70)
    print(df.head(3))
    print()
    print(df.info())
    print("\nMissing values:")
    print(df.isnull().sum()[df.isnull().sum() > 0])
    print("\n")

======================================================================
📌 CUSTOMERS  |  shape = (99441, 5)
----------------------------------------------------------------------
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 11.0 MB
None

Missing values:
Series([], dtype: int64)


======================================================================
📌 GEOLOCATION  |  shape = (1000163, 5)
----------------------------------------------------------------------
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  str
 4   geolocation_state            1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 50.1 MB
None

Missing values:
Series([], dtype: int64)


======================================================================
📌 ORDERS  |  shape = (99441, 8)
----------------------------------------------------------------------
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB
None

Missing values:
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64


======================================================================
📌 ORDER_ITEMS  |  shape = (112650, 7)
----------------------------------------------------------------------
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d

   shipping_limit_date  price  freight_value
0  2017-09-19 09:45:35   58.9          13.29
1  2017-05-03 11:05:13  239.9          19.93
2  2018-01-18 14:48:30  199.0          17.87

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 18.4 MB
None

Missing values:
Series([], dtype: int64)


======================================================================
📌 ORDER_PAYMENTS  |  shape = (103886, 5)
----------------------------------------------------------------------
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 8.1 MB
None

Missing values:
Series([], dtype: int64)


======================================================================
📌 ORDER_REVIEWS  |  shape = (99224, 7)
----------------------------------------------------------------------
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b

   review_score review_comment_title review_comment_message  \
0             4                  NaN                    NaN
1             5                  NaN                    NaN
2             5                  NaN                    NaN

  review_creation_date review_answer_timestamp
0  2018-01-18 00:00:00     2018-01-18 21:46:59
1  2018-03-10 00:00:00     2018-03-11 03:05:13
2  2018-02-17 00:00:00     2018-02-18 14:36:24

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 17.8 MB
None

Missing values:
review_comment_title      87656
review_comment_message    58247
dtype: int64


======================================================================
📌 PRODUCTS  |  shape = (32951, 9)
----------------------------------------------------------------------
                         product_id product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5            perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                 artes
2  96bd76ec8810374ed1b65e291975717f         esporte_lazer

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 3.7 MB
None

Missing values:
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64


======================================================================
📌 SELLERS  |  shape = (3095, 4)
----------------------------------------------------------------------
                          seller_id  seller_zip_code_prefix     seller_city  \
0  3442f8959a84dea7ee197c632cb2df15                   13023        campinas
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844      mogi guacu
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031  rio de janeiro

  seller_state
0           SP
1           SP
2           RJ

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 230.3 KB
None

Missing values:
Series([], dtype: int64)


======================================================================
📌 CATEGORY_TRANSLATION  |  shape = (71, 2)
----------------------------------------------------------------------
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 3.5 KB
None

Missing values:
Series([], dtype: int64)

In [13]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

In [10]:
# ============================================================
# 5. Key relationships & simple merges (most common)
# ============================================================
# Orders + customers
orders_customers = orders.merge(
    customers, on="customer_id", how="left"
)

# Order items + products + category translation
items_products = (
    order_items
    .merge(products, on="product_id", how="left")
    .merge(category_trans, on="product_category_name", how="left")
)

# Full order view (very useful)
full_orders = (
    orders
    .merge(order_items, on="order_id", how="left")
    .merge(order_payments, on="order_id", how="left")
    .merge(order_reviews, on="order_id", how="left")
    .merge(customers, on="customer_id", how="left")
    .merge(products, on="product_id", how="left")
    .merge(category_trans, on="product_category_name", how="left")
)

print("Full orders shape:", full_orders.shape)
display(full_orders.head())

Full orders shape: (119143, 37)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,customer_state,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,SP,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,595fac2a385ac33a80bd5114aec74eb8,...,BA,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,aa4383b373c6aca5d8797843e5594415,...,GO,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,auto